import Head from 'next/head'
import { Typography } from '@mui/material'

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <div>
        <Typography variant='h2'> Welcome to Next.js!</Typography>
      </div>
    </>
  )
}
