import Head from 'next/head'
import Sliders from './container/Sliders';

export default function Home() {

  return (
    <>
      <Head>
        <title>EProperty</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <main>
        <Sliders/>
      </main>
    </>
  )
}
