import Head from 'next/head'
import styles from '../styles/Home.module.css'
import { Typography } from '@mui/material'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Typography variant='h2'> Welcome to Next.js!</Typography>
      </main>
    </div>
  )
}
